// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PRECONDITIONMODEL_FASTBOTX_H_
#define FLATBUFFERS_GENERATED_PRECONDITIONMODEL_FASTBOTX_H_

#include "flatbuffers/flatbuffers.h"

namespace fastbotx {

struct PreconditionTemplate;
struct PreconditionTemplateBuilder;

struct PreconditionPage;
struct PreconditionPageBuilder;

struct PreconditionModel;
struct PreconditionModelBuilder;

struct PreconditionTemplate FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef PreconditionTemplateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LENGTH = 4,
    VT_SEQUENCE = 6,
    VT_RELIABILITY = 8
  };
  int32_t length() const {
    return GetField<int32_t>(VT_LENGTH, 0);
  }
  const flatbuffers::Vector<uint64_t> *sequence() const {
    return GetPointer<const flatbuffers::Vector<uint64_t> *>(VT_SEQUENCE);
  }
  const flatbuffers::Vector<double> *reliability() const {
    return GetPointer<const flatbuffers::Vector<double> *>(VT_RELIABILITY);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_LENGTH) &&
           VerifyOffset(verifier, VT_SEQUENCE) &&
           verifier.VerifyVector(sequence()) &&
           VerifyOffset(verifier, VT_RELIABILITY) &&
           verifier.VerifyVector(reliability()) &&
           verifier.EndTable();
  }
};

struct PreconditionTemplateBuilder {
  typedef PreconditionTemplate Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_length(int32_t length) {
    fbb_.AddElement<int32_t>(PreconditionTemplate::VT_LENGTH, length, 0);
  }
  void add_sequence(flatbuffers::Offset<flatbuffers::Vector<uint64_t>> sequence) {
    fbb_.AddOffset(PreconditionTemplate::VT_SEQUENCE, sequence);
  }
  void add_reliability(flatbuffers::Offset<flatbuffers::Vector<double>> reliability) {
    fbb_.AddOffset(PreconditionTemplate::VT_RELIABILITY, reliability);
  }
  explicit PreconditionTemplateBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<PreconditionTemplate> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<PreconditionTemplate>(end);
    return o;
  }
};

inline flatbuffers::Offset<PreconditionTemplate> CreatePreconditionTemplate(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t length = 0,
    flatbuffers::Offset<flatbuffers::Vector<uint64_t>> sequence = 0,
    flatbuffers::Offset<flatbuffers::Vector<double>> reliability = 0) {
  PreconditionTemplateBuilder builder_(_fbb);
  builder_.add_reliability(reliability);
  builder_.add_sequence(sequence);
  builder_.add_length(length);
  return builder_.Finish();
}

inline flatbuffers::Offset<PreconditionTemplate> CreatePreconditionTemplateDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t length = 0,
    const std::vector<uint64_t> *sequence = nullptr,
    const std::vector<double> *reliability = nullptr) {
  auto sequence__ = sequence ? _fbb.CreateVector<uint64_t>(*sequence) : 0;
  auto reliability__ = reliability ? _fbb.CreateVector<double>(*reliability) : 0;
  return fastbotx::CreatePreconditionTemplate(
      _fbb,
      length,
      sequence__,
      reliability__);
}

struct PreconditionPage FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef PreconditionPageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_HASHCODE = 4,
    VT_SCORE = 6,
    VT_TEMPLATES = 8
  };
  uint64_t hashcode() const {
    return GetField<uint64_t>(VT_HASHCODE, 0);
  }
  double score() const {
    return GetField<double>(VT_SCORE, 0.0);
  }
  const flatbuffers::Vector<flatbuffers::Offset<fastbotx::PreconditionTemplate>> *templates() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<fastbotx::PreconditionTemplate>> *>(VT_TEMPLATES);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_HASHCODE) &&
           VerifyField<double>(verifier, VT_SCORE) &&
           VerifyOffset(verifier, VT_TEMPLATES) &&
           verifier.VerifyVector(templates()) &&
           verifier.VerifyVectorOfTables(templates()) &&
           verifier.EndTable();
  }
};

struct PreconditionPageBuilder {
  typedef PreconditionPage Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_hashcode(uint64_t hashcode) {
    fbb_.AddElement<uint64_t>(PreconditionPage::VT_HASHCODE, hashcode, 0);
  }
  void add_score(double score) {
    fbb_.AddElement<double>(PreconditionPage::VT_SCORE, score, 0.0);
  }
  void add_templates(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<fastbotx::PreconditionTemplate>>> templates) {
    fbb_.AddOffset(PreconditionPage::VT_TEMPLATES, templates);
  }
  explicit PreconditionPageBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<PreconditionPage> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<PreconditionPage>(end);
    return o;
  }
};

inline flatbuffers::Offset<PreconditionPage> CreatePreconditionPage(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t hashcode = 0,
    double score = 0.0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<fastbotx::PreconditionTemplate>>> templates = 0) {
  PreconditionPageBuilder builder_(_fbb);
  builder_.add_score(score);
  builder_.add_hashcode(hashcode);
  builder_.add_templates(templates);
  return builder_.Finish();
}

inline flatbuffers::Offset<PreconditionPage> CreatePreconditionPageDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t hashcode = 0,
    double score = 0.0,
    const std::vector<flatbuffers::Offset<fastbotx::PreconditionTemplate>> *templates = nullptr) {
  auto templates__ = templates ? _fbb.CreateVector<flatbuffers::Offset<fastbotx::PreconditionTemplate>>(*templates) : 0;
  return fastbotx::CreatePreconditionPage(
      _fbb,
      hashcode,
      score,
      templates__);
}

struct PreconditionModel FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef PreconditionModelBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERSION = 4,
    VT_PAGES = 6
  };
  int32_t version() const {
    return GetField<int32_t>(VT_VERSION, 0);
  }
  const flatbuffers::Vector<flatbuffers::Offset<fastbotx::PreconditionPage>> *pages() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<fastbotx::PreconditionPage>> *>(VT_PAGES);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_VERSION) &&
           VerifyOffset(verifier, VT_PAGES) &&
           verifier.VerifyVector(pages()) &&
           verifier.VerifyVectorOfTables(pages()) &&
           verifier.EndTable();
  }
};

struct PreconditionModelBuilder {
  typedef PreconditionModel Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_version(int32_t version) {
    fbb_.AddElement<int32_t>(PreconditionModel::VT_VERSION, version, 0);
  }
  void add_pages(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<fastbotx::PreconditionPage>>> pages) {
    fbb_.AddOffset(PreconditionModel::VT_PAGES, pages);
  }
  explicit PreconditionModelBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<PreconditionModel> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<PreconditionModel>(end);
    return o;
  }
};

inline flatbuffers::Offset<PreconditionModel> CreatePreconditionModel(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t version = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<fastbotx::PreconditionPage>>> pages = 0) {
  PreconditionModelBuilder builder_(_fbb);
  builder_.add_pages(pages);
  builder_.add_version(version);
  return builder_.Finish();
}

inline flatbuffers::Offset<PreconditionModel> CreatePreconditionModelDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t version = 0,
    const std::vector<flatbuffers::Offset<fastbotx::PreconditionPage>> *pages = nullptr) {
  auto pages__ = pages ? _fbb.CreateVector<flatbuffers::Offset<fastbotx::PreconditionPage>>(*pages) : 0;
  return fastbotx::CreatePreconditionModel(
      _fbb,
      version,
      pages__);
}

inline const fastbotx::PreconditionModel *GetPreconditionModel(const void *buf) {
  return flatbuffers::GetRoot<fastbotx::PreconditionModel>(buf);
}

inline const fastbotx::PreconditionModel *GetSizePrefixedPreconditionModel(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<fastbotx::PreconditionModel>(buf);
}

inline const char *PreconditionModelIdentifier() {
  return "PCND";
}

inline bool PreconditionModelBufferHasIdentifier(const void *buf) {
  return flatbuffers::BufferHasIdentifier(
      buf, PreconditionModelIdentifier());
}

inline bool VerifyPreconditionModelBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fastbotx::PreconditionModel>(PreconditionModelIdentifier());
}

inline bool VerifySizePrefixedPreconditionModelBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fastbotx::PreconditionModel>(PreconditionModelIdentifier());
}

inline void FinishPreconditionModelBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<fastbotx::PreconditionModel> root) {
  fbb.Finish(root, PreconditionModelIdentifier());
}

inline void FinishSizePrefixedPreconditionModelBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<fastbotx::PreconditionModel> root) {
  fbb.FinishSizePrefixed(root, PreconditionModelIdentifier());
}

}  // namespace fastbotx

#endif  // FLATBUFFERS_GENERATED_PRECONDITIONMODEL_FASTBOTX_H_
